---
title: "Day27_Dots"
author: "Chen-Chia Ku"
date: "2023-11-27"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(ggplot2)
library(dplyr)
library(ggpubr)

library(sysfonts)
library(showtext)
```




```{r}
font_add_google(name = 'Raleway Dots', family = 'Raleway Dots')
showtext_auto()

```


```{r}
Podt <- read.csv("D:/Drive/6_Rworld/30daysMapChallenge_2023/pole.csv")

```

```{r}

TWD97TM2toWGS84 <- function (input_lat, input_lon){  
  # input_lat: TWD97橫座標, 南北緯度, latitude N
  # input_lon: TWD97縱座標, 東西經度, longitude E
  
  input_lat <- input_lat %>% as.character %>% as.numeric()
  input_lon <- input_lon %>% as.character %>% as.numeric()
  
  a = 6378137.0
  b = 6356752.314245
  lon0 = 121 * pi / 180
  k0 = 0.9999
  dx = 250000
  dy = 0
  e = (1 - b^2 / a^2)^0.5
  
  
  x =  input_lat - dx # input_lat: TWD97橫座標, 緯度, latitude
  y =  input_lon - dy # input_lon: TWD97縱座標, 經度, longitude
  
  M = y/k0
  
  mu = M/(a*(1.0 - ( e**2 )/4.0 - 3* (e**4)/64.0 - 5* (e**6)/256.0))
  e1 = (1.0 -  ((1.0 -  (e**2))**0.5)) / (1.0 +  ((1.0 -  (e**2))**0.5))
  
  J1 = (3*e1/2 - 27* (e1**3)/32.0)
  J2 = (21* (e1**2)/16 - 55* (e1**4)/32.0)
  J3 = (151* (e1**3)/96.0)
  J4 = (1097* (e1**4)/512.0)
  
  fp = mu + J1*sin(2*mu) + J2*sin(4*mu) + J3*sin(6*mu) + J4*sin(8*mu)
  
  e2 =  ((e*a/b)**2)
  C1 =  (e2*cos(fp)**2)
  T1 =  (tan(fp)**2)
  R1 = a*(1- (e**2))/ ((1- (e**2)* (sin(fp)**2))**(3.0/2.0))
  N1 = a/ ((1- (e**2)* (sin(fp)**2))**0.5)
  
  D = x/(N1*k0)
  
  #緯度計算 latitude
  Q1 = N1*tan(fp)/R1
  Q2 = ( (D**2)/2.0)
  Q3 = (5 + 3*T1 + 10*C1 - 4* (C1**2) - 9*e2)* (D**4)/24.0
  Q4 = (61 + 90*T1 + 298*C1 + 45* (T1**2) - 3* (C1**2) - 252*e2)* (D**6)/720.0
  lat = fp - Q1*(Q2 - Q3 + Q4)
  
  #經度計算 longitude
  Q5 = D
  Q6 = (1 + 2*T1 + C1)* (D**3)/6
  Q7 = (5 - 2*C1 + 28*T1 - 3* (C1**2) + 8*e2 + 24* (T1**2))* (D**5)/120.0
  lon = lon0 + (Q5 - Q6 + Q7)/cos(fp)
  
  
  lat = (lat*180) /pi #南北緯度  latitude 
  lon = (lon*180)/ pi #東西經度  longitude

  WGS = list(lat = lat, lon = lon)
  return(WGS)
}


```

```{r}
PoTai <- Podt %>%
  rename(County="縣市") %>%
  filter(!County %in% c("連江縣", "澎湖縣", "金門縣"))

```


```{r}

TransTai <- TWD97TM2toWGS84(PoTai$TWD_97_X,PoTai$TWD_97_Y)


PodtTai1 <- PoTai %>%
  mutate(LongWGS84=TransTai$lon, 
         LatWGS84=TransTai$lat) %>%
  filter(!LongWGS84>130)
```


```{r}
PoPlot <- ggplot(PodtTai1 , mapping=aes(x=LongWGS84, y=LatWGS84))+
  geom_point(size=0.000000001, color="#faf6b3", alpha=0.5)+
  #geom_text(mapping=aes(x=119.7, y=25.5, label="Telegraph pole"), 
  #          color="#faf6b3", size=50, family="Raleway Dots")+
  #geom_text(mapping=aes(x=119.7, y=25.5, label="Connecting and Lighting Up Our Lives"), 
  #          color="#faf6b3", size=50, family="Raleway Dots")+
  coord_sf(xlim = c(119.3, 122.5), crs=4326)+
  theme(panel.background = element_rect(fill = "#2E2E2E"), 
        plot.background = element_rect(fill = "#2E2E2E"),
        panel.grid = element_blank(), 
        plot.margin = margin(0, 0,0,0, "cm"),
        axis.text.x = element_text(vjust = 6, size=70, color="#7E7808"),
        axis.text.y = element_text(angle = 270, vjust = 6, hjust=0.5, size=70, color="#7E7808"),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        legend.position="none")
  

ggexport(PoPlot, filename = "Pole.png", width=7000, height = 8000, res=150)
```
