---
title: "Day16_"
author: "Chen-Chia Ku"
date: "2023-11-16"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(rnaturalearth)
library(rnaturalearthdata)
library(raster)
library(sf)
library(sysfonts)
library(showtext)
#library(osmdata)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(rgbif)
library(mapdata)
```

```{r}
font_add_google(name = 'Philosopher', family = 'Philosopher')
showtext_auto()

```


```{r}
myData<-occ_search(continent = "oceania", kingdomKey=6, basisOfRecord="PRESERVED_SPECIMEN")

```

```{r}
mydata2 <- myData$data %>%
  filter(!decimalLongitude==-156.134)


```

```{r}
world<- ne_countries(scale = "medium", returnclass = "sf") %>%
  dplyr::select(iso_a3, iso_n3, admin, continent)
Oceania_map <- world %>% 
  filter(continent=="Oceania") 

Land_DEM <- raster("D:/6_Rworld/30daysMapChallenge_2023/MapDt/HYP_LR_SR_OB_DR/HYP_LR_SR_OB_DR.tif")

```

```{r}

x <- aggregate(Land_DEM, fact=10)
Eledt <- rasterToPoints(x) 
Eledt2 <- as.data.frame(Eledt) %>%
  rename(elevation="HYP_LR_SR_OB_DR_1")


```





```{r}

mypal <- colorRampPalette(c("#d8b600", "#fff6c4"))

Oceania <- ggplot() +
  geom_tile(Eledt2, mapping=aes(x=x, y=y, fill=elevation))+
  geom_sf(data = Oceania_map , aes(group = admin),fill = "grey", color="#234A6D", alpha=0.3)+
  geom_sf_text(data = Oceania_map, aes(label=admin), size=22, family="Philosopher")+
  geom_point(mydata2, mapping=aes(x=decimalLongitude, y=decimalLatitude, color=scientificName ), size=0.1)+
  geom_text(mapping=aes(x=132, y=-52, label="Oceania"), 
            family="Philosopher", size=200, color="#97bdda")+
  scale_color_manual(values = mypal(308))+
  coord_sf(xlim=c(110, 180),ylim=c(-0.1, -65),  crs=4326)+
  theme(panel.background = element_rect(fill = "transparent", color="#234A6D"), 
        plot.background=element_rect(fill = "#1e405e", color="#234A6D"),
          panel.grid = element_blank(), 
          plot.margin = margin(0.5, -0.6, 0, 0, "cm"),
          axis.text.x = element_text(vjust = 8, size=40, color="#438BC4"),
          axis.text.y = element_text(angle = 270, vjust = 8, hjust=0.5, size=40, color="#438BC4"),
          axis.ticks.x = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          legend.position="none")


ggexport(Oceania, filename = "Oceania.png", width = 4890, height=5600, res=500)

```





