---
title: "Day29_Population"
author: "Chen-Chia Ku"
date: "2023-11-29"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(dplyr)
library(ggplot2)
library(sf)
library(rayshader)
library(ggspatial) #annotation_north_arrow
```


```{r}
TaiwanVg_shp <- sf::st_read(dsn = "D:/Drive/6_Rworld/30daysMapChallenge_2023/MapDt/TaiwanVillage", layer="VILLAGE_MOI_1081121")

Population <- read.csv("D:/Drive/6_Rworld/30daysMapChallenge_2023/Day3_Polygons/opendata111Y051.csv")

```


# Population data combine with Village shapefile
```{r}

Population1 <- Population %>%
  mutate(population=as.numeric(population)) %>%
  filter(!is.na(population)) %>%
  group_by(district_code, site_id, village) %>%
  summarise(people=sum(population, na.rm = T)) %>%
  ungroup() %>%
  rename(VILLCODE="district_code")
Population_low  <- Population1 %>%
  filter(!people>10100)

Population_high <-  Population1 %>%
  filter(people>10100)

TaiwanVglow_bind <- merge(TaiwanVg_shp, Population_low, by="VILLCODE")
TaiwanVghigh_bind <- merge(TaiwanVg_shp, Population_high, by="VILLCODE")

```

```{r}
mypal <- colorRampPalette(c("#153049","#443A83","#287D8E","#25AB82","#98CC48","#F0E51D","#f5ed67","#FAF6B3"))

Taiwan <- ggplot()+
  geom_sf(data=TaiwanVghigh_bind ,fill="#fbf8c5", colour=NA)+
  geom_sf(data=TaiwanVglow_bind ,mapping=aes(fill = people), colour=NA)+
  coord_sf(xlim = c(116, 126), ylim = c(19, 29), expand = FALSE, crs=4326)+
  scale_fill_gradientn(name="People live in \n the village",
                       colours = mypal(20), 
                       breaks=c(2500, 5000, 7500, 10000),
                       labels=c(2500, 5000, 7500, "30000"))+
  annotation_north_arrow(location = "tl", which_north = "true",   #North
                         pad_x = unit(9, "cm"), pad_y = unit(9, "cm"), 
                         height = unit(1.0, "cm"), width = unit(1.0, "cm") , 
                         style = north_arrow_fancy_orienteering(text_col = '#58574c', 
                                                                line_col = '#58574c',
                                                                fill = '#EDEAB9'))+
  theme(panel.background = element_rect(fill = "#2E2E2E", color="#2E2E2E"), 
        panel.grid = element_blank(), 
        plot.background = element_rect(fill = "#2E2E2E", color="#2E2E2E"),
        plot.margin = margin(0, 0, -0.4, -0.4, "cm"),
        axis.text.x = element_text(vjust = 8, size=8, color="#00b1b1"),
        axis.text.y = element_text(angle = 270, vjust = 7, hjust=0.5, size=8, color="#00b1b1"),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(), 
        legend.position = "none", 
        plot.title = element_text(vjust = -10))

Taiwan

```

```{r}
PoPBar <- plot_gg(Taiwan,multicore=T,width=10,height=10,scale=160, sunangle=130,
                    save_height_matrix = TRUE,windowsize = c(500, 500),
        background = "#2E2E2E")

render_label(PoPBar, text = "Population",x =1500, 
             y =900, z=70, linecolor = "#2E2E2E", textsize =7, 
             textcolor = "#faf6b3")

render_label(PoPBar, text = "#30DayMapChallenge | Day29_Population | @jjakon11",x =1500, 
             y =900, z=70, linecolor = "#2E2E2E", textsize =1.3, 
             textcolor = "#faf6b3")

```

```{r}
render_snapshot(filename = "3D_Population")



```

