---
title: "Day14_Europe"
author: "Chen-Chia Ku"
date: "2023-11-14"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(ggplot2)
library(dplyr)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(ggstar)

```

```{r}
world<- ne_countries(scale = 50, 
                     type = "countries", returnclass = "sf") %>%
  dplyr::select(iso_a3, iso_n3, admin, continent)

EU_map <- world %>% 
  filter(continent=="Europe") %>%
  mutate(cell=1:nrow(.))

VegeEU <- raster("D:/6_Rworld/30daysMapChallenge_2023/MapDt/2_FOR_HRL_forest_2015/TCD_2015_020m_at_31287_d02.tif")



VegeEU <- as.data.frame(VegeEU, xy=T, na.rm=T)

VegeEU <- sf::st_read(dsn = "D:/6_Rworld/30daysMapChallenge_2023/MapDt/EuropeVegetation", layer="vegetacao_natural_atual_limite") 

st_crs(VegeEU) = 4326

VegeEU2 <-projectRaster(VegeEU, proj4string(EU_map)) 


```

```{r}
ggplot()+
  geom_star(data=VegeEU)
  geom_sf(data = EU_map, alpha = 0.6)+
  geom_sf(data=VegeEU  , colour="#244C70")+
  coord_sf(crs=(4326))

```
